#!/usr/bin/env bash
# Transfer a local file to a remote server using scp
if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
sudo scp -i "$4" "$1" "$3@$2:$1"
