#!/usr/bin/env bash
# Install and configure a web server on a ubuntu machine
sudo apt-get install -y nginx;
REDIRECT="rewrite \^\/redirect_me\$ 52.23.152.105 permanent;"
sudo sed -i "s/# server_name_in_redirect off;/$REDIRECT/" /etc/nginx/nginx.conf
echo "Holberton School HELL YEAH" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
