#!/usr/bin/env bash
# Print information about the domain and optionally a subdomain as a second
# argument
# shellcheck disable=SC2086

subdomain_info() {
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -v SUB=$2 'FNR == 2 { printf "The subdomain "SUB" is a "$4" record and points to "$5"\n"}'
}

if [ -z "$2" ]
then
    for SUBDOMAIN in "www" "lb-01" "web-01" "web-02"
    do
	subdomain_info "$1" "$SUBDOMAIN"
    done
else
    subdomain_info "$1" "$2"
fi
