#!/usr/bin/env bash
# Configure nginx server with custom http header
sudo apt-get install -y nginx;
sudo sed -i "29i\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n       proxy_set_header X-Served-By $HOSTNAME" /etc/nginx/sites-enabled/default
echo "Holberton School HELL YEAH" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
