#!/usr/bin/env bash
# Configure a new Ubuntu machine as a load balancer
sudo apt-get update
sudo apt-get install haproxy
sudo sed -i "s@=0@=1@" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
add_config="\nlisten main-app 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption http-server-close\n\toption forwardfor\n\tserver 90-web-02 52.23.152.105:80 check\n\tserver $
sudo sed -i "23 a\ $add_config" /etc/haproxy/haproxy.cfg
sudo service haproxy start
