#!/usr/bin/env bash
# Print a string indefinitely, can't be killed with SIGTERM
trap 'echo "I am invincible!!!"' TERM
# shellcheck disable=SC2078
while [ true ];
do
    echo "To infinity and beyond"
    sleep 2
done
