#!/usr/bin/env bash
# Creates a file with the script's PID, runs an indefinite for loop that
# only terminates on SIGTERM AND SIGQUIT signals
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' TERM
trap 'echo "Y U no love me?!"' INT
echo $(pgrep -f 9-process_and_pid_file) | sudo tee /var/run/holbertonscript.pid > /dev/null
while [ true ];
do
    echo "To infinity and beyond"
    sleep 1
done
