#!/usr/bin/env bash
# This script prints "Holberton School" 20 times, replacing this with
# "bad luck from <country>" based on the unlucky number according to
# that country

I=1
while [ $I -le 20 ];
do
    echo "$I"
    case $I in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    I=$(( I + 1 ))
done
