#!/usr/bin/env bash
# Change the localhost to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i $'1 a\8.8.8.8\tfacebook.com' ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
